import { NextRequest, NextResponse } from "next/server";
import { getSupabaseClient } from "@/lib/supabase-client";

export async function GET(request: NextRequest) {
  try {
    const authHeader = request.headers.get("Authorization");
    const token = authHeader?.replace("Bearer ", "");
    if (!token) {
      return NextResponse.json({ error: "No token provided" }, { status: 401 });
    }

    const supabase = getSupabaseClient(token);
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);
    if (authError || !user) {
      return NextResponse.json({ error: authError?.message || "Invalid token" }, { status: 401 });
    }

    // Get credits from the database
    const { data: credits, error } = await supabase
      .from("user_credits")
      .select("total_credits, used_credits")
      .eq("user_id", user.id)
      .single();

    if (error) {
      // User might not have a credits record yet (very rare edge case)
      return NextResponse.json({
        total_credits: 0,
        used_credits: 0,
        remaining: 0,
      });
    }

    return NextResponse.json({
      total_credits: credits.total_credits,
      used_credits: credits.used_credits,
      remaining: credits.total_credits - credits.used_credits,
    });
  } catch (err) {
    console.error("Error fetching credits:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Internal server error" },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const authHeader = request.headers.get("Authorization");
    const token = authHeader?.replace("Bearer ", "");
    if (!token) {
      return NextResponse.json({ error: "No token provided" }, { status: 401 });
    }

    const supabase = getSupabaseClient(token);
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);
    if (authError || !user) {
      return NextResponse.json({ error: authError?.message || "Invalid token" }, { status: 401 });
    }

    const body = await request.json();
    const { action, pages } = body;

    if (action === "deduct") {
      const numPages = typeof pages === "number" ? pages : 1;

      // Check current credits
      const { data: credits, error: fetchError } = await supabase
        .from("user_credits")
        .select("total_credits, used_credits")
        .eq("user_id", user.id)
        .single();

      if (fetchError) {
        return NextResponse.json({ error: "Failed to fetch credits" }, { status: 500 });
      }

      const remaining = credits.total_credits - credits.used_credits;
      if (remaining < numPages) {
        return NextResponse.json({
          error: "Insufficient credits",
          remaining,
          needed: numPages,
        }, { status: 403 });
      }

      // Deduct credits
      const { error: updateError } = await supabase
        .from("user_credits")
        .update({ used_credits: credits.used_credits + numPages, updated_at: new Date().toISOString() })
        .eq("user_id", user.id);

      if (updateError) {
        return NextResponse.json({ error: "Failed to deduct credits" }, { status: 500 });
      }

      return NextResponse.json({
        success: true,
        deducted: numPages,
        remaining: remaining - numPages,
      });
    }

    if (action === "purchase") {
      const { plan } = body;
      const plans: Record<string, { credits: number; price: number }> = {
        "trial":   { credits: 30,  price: 9.9 },
        "basic":   { credits: 70,  price: 19.9 },
        "pro":     { credits: 180, price: 49.9 },
      };

      let selectedPlan: { credits: number; price: number } | null = null;
      let customAmount: number | null = null;

      if (plan === "custom" && body.credits) {
        const c = parseInt(body.credits, 10);
        if (isNaN(c) || c < 1) {
          return NextResponse.json({ error: "Invalid credit amount" }, { status: 400 });
        }
        customAmount = c;
        selectedPlan = { credits: c, price: Math.round(c * 0.33 * 100) / 100 };
      } else if (plan && plans[plan]) {
        selectedPlan = plans[plan];
      } else {
        return NextResponse.json({ error: "Invalid plan" }, { status: 400 });
      }

      // Return order info – actual payment integration will be added
      return NextResponse.json({
        order: {
          userId: user.id,
          credits: selectedPlan.credits,
          amount: selectedPlan.price,
          description: plan === "custom"
            ? `自定义充值 ${customAmount} 次`
            : `套餐充值 ${selectedPlan.credits} 次`,
        },
        // Payment URL will be generated by the payment integration
        paymentUrl: null,
      });
    }

    return NextResponse.json({ error: "Invalid action" }, { status: 400 });
  } catch (err) {
    console.error("Error processing credits:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Internal server error" },
      { status: 500 }
    );
  }
}